spring:
  application:
    name: kloset-chat

  profiles:
    active: ${SPRING_PROFILE}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

  endpoint:
    prometheus:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8081
